/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pillar(props) {
  const { nodes, materials } = useGLTF('/pillars.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[2, 2, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[0, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Material}
        position={[0, 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Material}
        position={[0, 8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
        position={[0, 10, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[0, 12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Material}
        position={[0, 14, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.Material}
        position={[0, 16, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.Material}
        position={[-4, 0, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.Material}
        position={[-4, 2, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.Material}
        position={[-4, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials.Material}
        position={[-4, 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.Material}
        position={[-4, 8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials.Material}
        position={[-4, 10, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials.Material}
        position={[-4, 12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials.Material}
        position={[-4, 14, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.Material}
        position={[-4, 16, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials.Material}
        position={[-8, 0, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.Material}
        position={[-8, 2, -2]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.Material}
        position={[-8, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials.Material}
        position={[-8, 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.Material}
        position={[-8, 8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials.Material}
        position={[-8, 10, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials.Material}
        position={[-8, 12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.Material}
        position={[-8, 14, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials.Material}
        position={[-8, 16, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.Material}
        position={[-12, 0, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.Material}
        position={[-12, 2, -2]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials.Material}
        position={[-12, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials.Material}
        position={[-12, 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials.Material}
        position={[-12, 8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.Material}
        position={[-12, 10, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.Material}
        position={[-12, 12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.Material}
        position={[-12, 14, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials.Material}
        position={[-12, 16, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials.Material}
        position={[-16, 0, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials.Material}
        position={[-16, 2, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials.Material}
        position={[-16, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials.Material}
        position={[-16, 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials.Material}
        position={[-16, 8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials.Material}
        position={[-16, 10, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials.Material}
        position={[-16, 12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials.Material}
        position={[-16, 14, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials.Material}
        position={[-16, 16, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials.Material}
        position={[-20, 0, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials.Material}
        position={[-22, 2, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials.Material}
        position={[-20, 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={materials.Material}
        position={[-20, 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials.Material}
        position={[-20, 8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube050.geometry}
        material={materials.Material}
        position={[-20, 10, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={materials.Material}
        position={[-20, 12, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={materials.Material}
        position={[-20, 14, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials.Material}
        position={[-20, 16, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={materials.Material}
        position={[0, 0, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055.geometry}
        material={materials.Material}
        position={[0, 2, 38]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056.geometry}
        material={materials.Material}
        position={[0, 4, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={materials.Material}
        position={[0, 6, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058.geometry}
        material={materials.Material}
        position={[0, 8, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059.geometry}
        material={materials.Material}
        position={[0, 10, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060.geometry}
        material={materials.Material}
        position={[0, 12, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061.geometry}
        material={materials.Material}
        position={[0, 14, 40]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062.geometry}
        material={materials.Material}
        position={[0, 16, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063.geometry}
        material={materials.Material}
        position={[-4, 0, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064.geometry}
        material={materials.Material}
        position={[-4, 2, 39]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials.Material}
        position={[-4, 4, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials.Material}
        position={[-4, 6, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067.geometry}
        material={materials.Material}
        position={[-4, 8, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials.Material}
        position={[-4, 10, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials.Material}
        position={[-4, 12, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070.geometry}
        material={materials.Material}
        position={[-4, 14, 40]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials.Material}
        position={[-4, 16, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials.Material}
        position={[-8, 0, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials.Material}
        position={[-8, 2, 42]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube074.geometry}
        material={materials.Material}
        position={[-8, 4, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075.geometry}
        material={materials.Material}
        position={[-8, 6, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={materials.Material}
        position={[-8, 8, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube077.geometry}
        material={materials.Material}
        position={[-8, 10, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube078.geometry}
        material={materials.Material}
        position={[-8, 12, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube079.geometry}
        material={materials.Material}
        position={[-8, 14, 40]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube080.geometry}
        material={materials.Material}
        position={[-8, 16, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081.geometry}
        material={materials.Material}
        position={[-12, 0, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube082.geometry}
        material={materials.Material}
        position={[-12, 2, 42]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083.geometry}
        material={materials.Material}
        position={[-12, 4, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube084.geometry}
        material={materials.Material}
        position={[-12, 6, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube085.geometry}
        material={materials.Material}
        position={[-12, 8, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube086.geometry}
        material={materials.Material}
        position={[-12, 10, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube087.geometry}
        material={materials.Material}
        position={[-12, 12, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube088.geometry}
        material={materials.Material}
        position={[-12, 14, 40]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube089.geometry}
        material={materials.Material}
        position={[-12, 16, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube090.geometry}
        material={materials.Material}
        position={[-16, 0, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube091.geometry}
        material={materials.Material}
        position={[-16, 2, 39]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube092.geometry}
        material={materials.Material}
        position={[-16, 4, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube093.geometry}
        material={materials.Material}
        position={[-16, 6, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube094.geometry}
        material={materials.Material}
        position={[-16, 8, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube095.geometry}
        material={materials.Material}
        position={[-16, 10, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube096.geometry}
        material={materials.Material}
        position={[-16, 12, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube097.geometry}
        material={materials.Material}
        position={[-16, 14, 40]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube098.geometry}
        material={materials.Material}
        position={[-16, 16, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube099.geometry}
        material={materials.Material}
        position={[-20, 0, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube100.geometry}
        material={materials.Material}
        position={[-20, 2, 38]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube101.geometry}
        material={materials.Material}
        position={[-20, 4, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube102.geometry}
        material={materials.Material}
        position={[-20, 6, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube103.geometry}
        material={materials.Material}
        position={[-20, 8, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube104.geometry}
        material={materials.Material}
        position={[-20, 10, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube105.geometry}
        material={materials.Material}
        position={[-20, 12, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube106.geometry}
        material={materials.Material}
        position={[-20, 14, 40]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube107.geometry}
        material={materials.Material}
        position={[-20, 16, 40]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube108.geometry}
        material={materials.Material}
        position={[-20, 0, 4]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube109.geometry}
        material={materials.Material}
        position={[-20, 16, 4]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube110.geometry}
        material={materials.Material}
        position={[-20, 0, 8]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube111.geometry}
        material={materials.Material}
        position={[-17, 2, 8]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube112.geometry}
        material={materials.Material}
        position={[-20, 4, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube113.geometry}
        material={materials.Material}
        position={[-20, 6, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube114.geometry}
        material={materials.Material}
        position={[-20, 8, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube115.geometry}
        material={materials.Material}
        position={[-20, 10, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube116.geometry}
        material={materials.Material}
        position={[-20, 12, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube117.geometry}
        material={materials.Material}
        position={[-20, 14, 8]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube118.geometry}
        material={materials.Material}
        position={[-20, 16, 8]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube119.geometry}
        material={materials.Material}
        position={[-20, 0, 12]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube120.geometry}
        material={materials.Material}
        position={[-20, 16, 12]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube121.geometry}
        material={materials.Material}
        position={[-20, 0, 16]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube122.geometry}
        material={materials.Material}
        position={[-20, 2, 18]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube123.geometry}
        material={materials.Material}
        position={[-20, 4, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube124.geometry}
        material={materials.Material}
        position={[-20, 6, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube125.geometry}
        material={materials.Material}
        position={[-20, 8, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube126.geometry}
        material={materials.Material}
        position={[-20, 10, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube127.geometry}
        material={materials.Material}
        position={[-20, 12, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube128.geometry}
        material={materials.Material}
        position={[-20, 14, 16]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube129.geometry}
        material={materials.Material}
        position={[-20, 16, 16]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube130.geometry}
        material={materials.Material}
        position={[-20, 0, 20]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube131.geometry}
        material={materials.Material}
        position={[-20, 16, 20]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube132.geometry}
        material={materials.Material}
        position={[-20, 0, 24]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube133.geometry}
        material={materials.Material}
        position={[-22, 2, 26]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube134.geometry}
        material={materials.Material}
        position={[-20, 4, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube135.geometry}
        material={materials.Material}
        position={[-20, 6, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube136.geometry}
        material={materials.Material}
        position={[-20, 8, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube137.geometry}
        material={materials.Material}
        position={[-20, 10, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube138.geometry}
        material={materials.Material}
        position={[-20, 12, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube139.geometry}
        material={materials.Material}
        position={[-20, 14, 24]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube140.geometry}
        material={materials.Material}
        position={[-20, 16, 24]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube141.geometry}
        material={materials.Material}
        position={[-20, 0, 28]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube142.geometry}
        material={materials.Material}
        position={[-20, 16, 28]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube143.geometry}
        material={materials.Material}
        position={[-20, 0, 32]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube144.geometry}
        material={materials.Material}
        position={[-18, 2, 32]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube145.geometry}
        material={materials.Material}
        position={[-20, 4, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube146.geometry}
        material={materials.Material}
        position={[-20, 6, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube147.geometry}
        material={materials.Material}
        position={[-20, 8, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube148.geometry}
        material={materials.Material}
        position={[-20, 10, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube149.geometry}
        material={materials.Material}
        position={[-20, 12, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube150.geometry}
        material={materials.Material}
        position={[-20, 14, 32]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube151.geometry}
        material={materials.Material}
        position={[-20, 16, 32]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube152.geometry}
        material={materials.Material}
        position={[-20, 0, 36]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube153.geometry}
        material={materials.Material}
        position={[-20, 16, 36]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube154.geometry}
        material={materials.Material}
        position={[0, 0, 4]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube155.geometry}
        material={materials.Material}
        position={[0, 16, 4]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube156.geometry}
        material={materials.Material}
        position={[0, 0, 8]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157.geometry}
        material={materials.Material}
        position={[2, 2, 8]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube158.geometry}
        material={materials.Material}
        position={[0, 4, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube159.geometry}
        material={materials.Material}
        position={[0, 6, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube160.geometry}
        material={materials.Material}
        position={[0, 8, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube161.geometry}
        material={materials.Material}
        position={[0, 10, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube162.geometry}
        material={materials.Material}
        position={[0, 12, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube163.geometry}
        material={materials.Material}
        position={[0, 14, 8]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube164.geometry}
        material={materials.Material}
        position={[0, 16, 8]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube165.geometry}
        material={materials.Material}
        position={[0, 0, 12]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube166.geometry}
        material={materials.Material}
        position={[0, 16, 12]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube167.geometry}
        material={materials.Material}
        position={[0, 0, 16]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube168.geometry}
        material={materials.Material}
        position={[0, 2, 16]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube169.geometry}
        material={materials.Material}
        position={[0, 4, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube170.geometry}
        material={materials.Material}
        position={[0, 6, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube171.geometry}
        material={materials.Material}
        position={[0, 8, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube172.geometry}
        material={materials.Material}
        position={[0, 10, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube173.geometry}
        material={materials.Material}
        position={[0, 12, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube174.geometry}
        material={materials.Material}
        position={[0, 14, 16]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube175.geometry}
        material={materials.Material}
        position={[0, 16, 16]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube176.geometry}
        material={materials.Material}
        position={[0, 0, 20]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube177.geometry}
        material={materials.Material}
        position={[0, 16, 20]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube178.geometry}
        material={materials.Material}
        position={[0, 0, 24]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube179.geometry}
        material={materials.Material}
        position={[2, 2, 24]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube180.geometry}
        material={materials.Material}
        position={[0, 4, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube181.geometry}
        material={materials.Material}
        position={[0, 6, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube182.geometry}
        material={materials.Material}
        position={[0, 8, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube183.geometry}
        material={materials.Material}
        position={[0, 10, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube184.geometry}
        material={materials.Material}
        position={[0, 12, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube185.geometry}
        material={materials.Material}
        position={[0, 14, 24]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube186.geometry}
        material={materials.Material}
        position={[0, 16, 24]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube187.geometry}
        material={materials.Material}
        position={[0, 0, 28]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube188.geometry}
        material={materials.Material}
        position={[0, 16, 28]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube189.geometry}
        material={materials.Material}
        position={[0, 0, 32]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube190.geometry}
        material={materials.Material}
        position={[2.001, 1.999, 29.998]}
        rotation={[0, 0.027, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube191.geometry}
        material={materials.Material}
        position={[0, 4, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube192.geometry}
        material={materials.Material}
        position={[0, 6, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube193.geometry}
        material={materials.Material}
        position={[0, 8, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube194.geometry}
        material={materials.Material}
        position={[0, 10, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube195.geometry}
        material={materials.Material}
        position={[0, 12, 32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube196.geometry}
        material={materials.Material}
        position={[0, 14, 32]}
        scale={[1.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube197.geometry}
        material={materials.Material}
        position={[0, 16, 32]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube198.geometry}
        material={materials.Material}
        position={[0, 0, 36]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube199.geometry}
        material={materials.Material}
        position={[0, 16, 36]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube200.geometry}
        material={materials['Material.001']}
        position={[-26, -2, 44]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube201.geometry}
        material={materials['Material.002']}
        position={[-26, -4, 44]}
        scale={[2, 1, 2]}
      />
    </group>
  )
}

useGLTF.preload('/pillars.glb')

